site_name: Moe's Page
docs_dir: '../../docs/zh'
site_dir: '../../generated/zh'


theme:
  name: material
  custom_dir: '../../overrides/'                  # This is where the customization of the theme lives
  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list


extra:
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: 简体中文
      link: /zh/
      lang: zh
  
  social:
    - icon: fontawesome/brands/github-alt
      name: My Github
      link: https://github.com/Shocked-Pikachu
    - icon: /fontawesome/regular/envelope
      name: Send Me An Email
      link: mailto:<mohy@stu.pku.edu.cn>


plugins:
  - search

copyright: |
  &copy; 2024 <a href="https://github.com/Shocked-Pikachu" target="_blank" rel="noopener"> Haoyu Mo</a>